workflows:
    version: 2
    build_and_test:
        jobs:
            - build:
                filters:
                    branches:
                        only: dev

            - test_dev:
                filters:
                    branches:
                        only: dev
                requires:
                    - build

            # - deploy_stage

version: 2
jobs:
    build:
        working_directory: ~/springboot
        # executer: docker, linux VM, mac VM
        docker:
            - image: circleci/openjdk:8-jdk    # primary image 8-jdk-browsers
              environment:
                  POSTGRES_DB: circle_test
                  # POSTGRES_USER: postgres    (default user)

            - image: circleci/postgres:9-alpine

        # build steps
        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "build.gradle" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

            - run: gradle dependencies    # listet sie nur! kein download!

            - save_cache:
                paths:
                    - ~/springboot/.gradle
                key: v1-dependencies-{{ checksum "build.gradle" }}

            # Compile code and run unit tests
            - run: gradle test

            - store_test_results:
                path: ~/springboot/build/reports/tests/test/
                # index.html hast some interessting reports
                # think about uploading this files to a http server

            # Run application and execute integration tests
            - run: gradle bootRun
            - run: curl localhost:8080    # should return Hello World
            # here will be actual robot tests - API, GUI

            # Package Jar/War files and deploy
            - run: gradle bootJar
            # - run: gradle bootWar
            - store_artifacts:
                path: ~/springboot/build/libs/*.war

            # Clean Up
            # - run: gradle clean
    test_dev:
        working_directory: ~/springboot
        docker:
            - image: busybox
              environment:
                  POSTGRES_DB: circle_test

        steps:
            - run: echo "HELLO JAVA"
